name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  perl:
    name: Perl (linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.14-buster'
          - '5.16-buster'
          - '5.18-buster'
          - '5.20-buster'
          - '5.22-buster'
          - '5.24-buster'
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.32'
          - '5.34'
          - '5.36'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install dependencies with cpanm
        uses: perl-actions/install-with-cpanm@8ec40bce95c287169e8c13551e5e49d0185ce955 # v2.2
        with:
          cpanfile: "cpanfile"
          sudo: false
      - name: Install Dependencies
        run: |
          apt-get install make gcc libssl-dev;
      - name: Build Module
        run: |
          perl Makefile.PL;
          make
      - name: Run Tests
        run: prove -lr -l -b t
