name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  perl:
    name: Perl (linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.14-buster'
          - '5.16-buster'
          - '5.18-buster'
          - '5.20-buster'
          - '5.22-buster'
          - '5.24-buster'
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.32'
          - '5.34'
          - '5.36'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          persist-credentials: false
      - name: uses install-with-cpanm
        uses: perl-actions/install-with-cpanm@10d60f00b4073f484fc29d45bfbe2f776397ab3d # v1.7
        with:
          cpanfile: "cpanfile"
          sudo: false
      - name: Install Dependencies
        run: |
          apt-get install make gcc libssl-dev;
      - name: Build Module
        run: |
          perl Makefile.PL;
          make
      - name: Run Tests
        run: prove -lr -l -b -I inc t
