name: zizmor

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '*'

env:
  ZIZMOR_VERSION: 1.26.1

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    name: zizmor via PyPI
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for uploading SARIF files
      contents: read         # Needed to clone the repository
      actions: read          # Needed for upload-sarif metadata
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: Run zizmor 🌈
        run: uvx "zizmor@${ZIZMOR_VERSION}" --format=sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional: enables online audits

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81 # v4.37.3
        with:
          sarif_file: results.sarif
          category: zizmor
